<?php

namespace AppBundle\Repository;

/**
 * CategoriePieceDetacheRepositoryTranslation
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriePieceDetacheRepositoryTranslation extends \Doctrine\ORM\EntityRepository
{
}
