<?php

namespace AppBundle\Repository;

/**
 * CategoriePieceDetacheTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriePieceDetacheTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
