<?php

namespace AppBundle\Repository;

/**
 * CategoriePieceDetacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriePieceDetacheRepository extends \Doctrine\ORM\EntityRepository
{
}
