<?php

namespace AppBundle\Repository;

/**
 * PieceDetacheTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceDetacheTranslationRepository extends \Doctrine\ORM\EntityRepository
{

    public function recuperePieceDeatacheDeLangue($langue)
    {
        return $this
            ->createQueryBuilder('p')
            ->where('c.name LIKE :pattern')
            ->setParameter('pattern', $langue);
    }
}
