<?php

namespace AppBundle\Repository;

/**
 * PieceDetacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceDetacheRepository extends \Doctrine\ORM\EntityRepository
{
}
