<?php

namespace AppBundle\Repository;

/**
 * PieceDetacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceDetacheRepository extends \Doctrine\ORM\EntityRepository {

      public function getPieceParCategorie($slug){
        
        $results = $this
                ->createQueryBuilder('piecedet')
                //->select('piecedet.id piecedet.prix, piecedet.image')
                ->join('piecedet.categoriePieceDetache', 'catpiedet')
                ->addSelect('catpiedet')
                ->join('catpiedet.translations', 'catpiedetrans')
                ->addSelect('catpiedetrans')
                ->where("catpiedetrans.slug = :slug")
                ->setParameter('slug', $slug )
                ->getQuery()
                ->getResult();
                
           return $results;
                
        
    }
    
}
