<?php

namespace AppBundle\Repository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractRepository
{
    
    public function getUserUsernamePasswoord($data){
        
        $results = $this
                ->createQueryBuilder('user')
                //->select('piecedet.id piecedet.prix, piecedet.image')
                ->join('user.roles', 'role')
                ->addSelect('role')
                ->where("user.username = :username AND user.password = :password ")
                ->setParameters([
                    'username' => $data->getUsername(),
                    'password' => $data->getPassword()
                ])
                ->getQuery()
                ->getResult();
                
           return $results;
                
        
    }

    public function findAllQueryBuilder($order = 'asc', $limit = 20, $offset = 0)
    {

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.id', $order);

        return $this->paginate($qb, $limit, $offset);
    }
 
    
    public function getUserByUsername($motArechercher) {
        
        //echo 'test';
        
        $results = $this
                ->createQueryBuilder('user')
                ->where("user.username LIKE '%". $motArechercher ."'")
                ->getQuery()
                ->getResult();
                
           return $results;
               
    }
    
}
