<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getUserUsernamePasswoord($data){
        
        $results = $this
                ->createQueryBuilder('user')
                //->select('piecedet.id piecedet.prix, piecedet.image')
                ->join('user.roles', 'role')
                ->addSelect('role')
                ->where("user.username = :username AND user.password = :password ")
                ->setParameters([
                    'username' => $data->getUsername(),
                    'password' => $data->getPassword()
                ])
                ->getQuery()
                ->getResult();
                
           return $results;
                
        
    }
    
}
