<?php

namespace AppBundle\Repository;

/**
 * VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVoitureParSlug($slug)
    {
        $results = $this
                ->createQueryBuilder('voiture')
                ->join('voiture.marque', 'marque')
                ->where('marque.slug = :slug')
                ->setParameter('slug', $slug)
                ->getQuery()
                ->getResult();
        
        return $results;
    }
    
    
}
