# app/config/security.yml
security:
    encoders:
        AppBundle\Entity\User: plaintext

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: app.security.login
                check_path: app.security.login
                default_target_path: app.redirect.by.role
            logout:
                path: app.security.logout
                target: app.homepage.index 
            provider: our_db_provider
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER